root: true

extends: r1cebank

parserOptions:
  ecmaVersion: 8

rules:

  no-return-assign: off
  no-lonely-if: off
  arrow-body-style: off
  array-callback-return: off
  dot-notation: warn
  max-len:
    - error
    - 120
  indent:
    - error
    - 4
    -
      SwitchCase: 1
